apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  alert.rules.yml: |
    groups:
    - name: uptime-monitor
      interval: 30s
      rules:
      - alert: API Gateway Down
        expr: up{job="uptime-pods"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "API Gateway pod is down"
          description: "Pod {{ $labels.pod }} has been down for more than 30 seconds."
