apiVersion: v1
kind: Secret
metadata:
  name: uptime-secret
  namespace: uptime-monitor
type: Opaque
data:
  POSTGRES_PASSWORD: dXB0aW1lX3Bhc3M=
  POSTGRES_USER: dXB0aW1lX3VzZXI=
  POSTGRES_DB: dXB0aW1lX2Ri
